/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as vrc25Sol from "./VRC25.sol";
export { ECDSA__factory } from "./ECDSA__factory";
export { ERC165__factory } from "./ERC165__factory";
