/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vrc25Sol from "./VRC25.sol";
export type { vrc25Sol };
export type { ECDSA } from "./ECDSA";
export type { ERC165 } from "./ERC165";
