/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC165 } from "./IERC165";
export type { IVRC25 } from "./IVRC25";
export type { VRC25 } from "./VRC25";
